AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Description: Environment
    Type: String
  System:
    Description: System Name
    Type: String
Resources:
  CodeConnections:
    UpdateReplacePolicy: Retain
    Type: AWS::CodeConnections::Connection
    Properties:
      ConnectionName: !Sub ${Env}--${System}--connections
      ProviderType: "GitHub"
      Tags:
        - Key: Name
          Value: !Sub ${Env}--${System}--connections
Outputs:
  CodeConnections:
    Description: Code Connections
    Value: !Ref CodeConnections
    Export:
      Name: !Sub ${AWS::StackName}--connections
