AWSTemplateFormatVersion: 2010-09-09
Description: Code Connections Stack
Parameters:
  System:
    Description: System Name
    Type: String
  Env:
    Description: Environment
    Type: String
Resources:
  CodeConnections:
    Type: AWS::CodeConnections::Connection
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      ConnectionName: !Sub ${System}-${Env}-connections
      ProviderType: "GitHub"
      Tags:
        - Key: Name
          Value: !Sub ${System}-${Env}-connections
Outputs:
  CodeConnections:
    Description: Code Connections
    Value: !Ref CodeConnections
    Export:
      Name: !Sub ${AWS::StackName}-connections-arn
